version: 1.0.{build}
pull_requests:
  do_not_increment_build_number: true
image: Visual Studio 2015
configuration: Release
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}.{build}'
  assembly_file_version: '{version}.{build}'
  assembly_informational_version: '{version}.{build}'
before_build:
- ps: nuget restore src\SpentBook.FileHelper.Parser.sln
build:
  publish_nuget: true
  verbosity: minimal
deploy:
- provider: NuGet
  api_key:
    secure: hOERhlJ1GXuewDdllLMZB8EEwMCEKs41GxZ+loFbEZAPgP4PvtOa9D/A3f5a1Tfy
  skip_symbols: true
  on:
    branch: master